title: Launch A New Project
tagline: Toolkit launching your new project. 10 min set up!
description: Make a launch site for your new webpage. Add an email list, HTTPS, free webhosting
url: http://drewrwilson.github.io/launch-a-new-project

mailchimpURI:
mailchimpAntiSpamCode:
logo: /images/logo.png

showPrivacyPolicy: false

socialMediaImage: /images/logo.png
twitter:
facebook:
instagram:
