title: Launch A New Project
tagline: Toolkit for launching your new project. Live in 15min!
description: Make a launch site for your new webpage. Add an email list, HTTPS, free webhosting
url: https://drewrwilson.com/launch-toolkit

logo: /images/logo.png
backgroundImage: 

mailchimpURI:
mailchimpAntiSpamCode:

showPrivacyPolicy: false

socialMediaImage: /images/logo.png
twitter:
facebook:
instagram:
